# Generated by Django 6.0.2 on 2026-02-12 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(unique=True)),
                ('source', models.CharField(blank=True, max_length=100)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('raw', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
