# Generated by Django 6.0.2 on 2026-02-13 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_newsarticle'),
    ]

    operations = [
        migrations.CreateModel(
            name='DripSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('as_of', models.DateField()),
                ('capital', models.FloatField()),
                ('dividend_income', models.FloatField()),
                ('yield_rate', models.FloatField()),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
            options={
                'ordering': ['-as_of'],
                'unique_together': {('portfolio', 'as_of')},
            },
        ),
    ]
