# Generated by Django 6.0.2 on 2026-02-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_dripsnapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='latest_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_price_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('close_price', models.FloatField()),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.stock')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('stock', 'date')},
            },
        ),
    ]
