# Generated by Django 6.0.2 on 2026-02-13 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0009_account_accounttransaction_dividend_portfoliodigest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PennySignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('as_of', models.DateField()),
                ('pattern_score', models.FloatField()),
                ('sentiment_score', models.FloatField()),
                ('hype_score', models.FloatField()),
                ('liquidity_score', models.FloatField()),
                ('combined_score', models.FloatField()),
                ('last_price', models.FloatField(blank=True, null=True)),
                ('avg_volume', models.FloatField(blank=True, null=True)),
                ('mentions', models.IntegerField(default=0)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-combined_score'],
                'unique_together': {('symbol', 'as_of')},
            },
        ),
    ]
