# Generated by GitHub Copilot on 2026-02-14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0011_stock_day_low_day_high'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaperTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.IntegerField()),
                ('entry_date', models.DateTimeField(auto_now_add=True)),
                ('stop_loss', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='OPEN', max_length=10)),
                ('pnl', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('exit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('exit_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
    ]
