# Generated by Django 6.0.2 on 2026-02-14 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0012_papertrade'),
        ('portfolio', '0014_macroindicator'),
    ]

    operations = [
    ]
