# Generated by Django 6.0.2 on 2026-02-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0015_merge_0012_papertrade_0014_macroindicator'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='entry_features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='papertrade',
            name='entry_signal',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
