# Generated by Django 6.0.2 on 2026-02-16 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0025_indexes_and_trade_logs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsarticle',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='stocknews',
            name='url',
            field=models.URLField(max_length=500, unique=True),
        ),
    ]
