# Generated by Django 6.0.2 on 2026-02-27 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0030_merge_0028_system_log_0029_merge_0028_master_watchlist_entry_0028_papertrade_broker_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='broker',
            field=models.CharField(choices=[('SIM', 'SIM'), ('ALPACA', 'ALPACA'), ('SHADOW', 'SHADOW')], db_index=True, default='SIM', max_length=20),
        ),
    ]
