# Generated by Django 6.0.3 on 2026-03-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0032_prediction_confidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='sandbox',
            field=models.CharField(choices=[('WATCHLIST', 'WATCHLIST'), ('AI_BLUECHIP', 'AI_BLUECHIP'), ('AI_PENNY', 'AI_PENNY'), ('AI_CRYPTO', 'AI_CRYPTO')], db_index=True, default='WATCHLIST', max_length=20),
        ),
        migrations.AlterField(
            model_name='sandboxwatchlist',
            name='sandbox',
            field=models.CharField(choices=[('WATCHLIST', 'WATCHLIST'), ('AI_BLUECHIP', 'AI_BLUECHIP'), ('AI_PENNY', 'AI_PENNY'), ('AI_CRYPTO', 'AI_CRYPTO')], max_length=20, unique=True),
        ),
    ]
