# Generated by Django 6.0.2 on 2026-08-07 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0033_alter_papertrade_sandbox_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sandboxwatchlist',
            name='symbol_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
