# Generated by Django 6.1 on 2026-08-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0034_sandboxwatchlist_symbol_sources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='sandbox',
            field=models.CharField(choices=[('WATCHLIST', 'WATCHLIST'), ('AI_BLUECHIP', 'AI_BLUECHIP'), ('AI_PENNY', 'AI_PENNY'), ('AI_CRYPTO', 'AI_CRYPTO'), ('FUNDAMENTAL_LAB', 'FUNDAMENTAL_LAB')], db_index=True, default='WATCHLIST', max_length=20),
        ),
    ]
