# Generated by Django 6.1 on 2026-08-11 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0035_alter_papertrade_sandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='broker',
            field=models.CharField(choices=[('SIM', 'SIM'), ('ALPACA', 'ALPACA'), ('SHADOW', 'SHADOW'), ('ALPACA_LAB', 'ALPACA_LAB')], db_index=True, default='SIM', max_length=20),
        ),
    ]
