# Generated by Django 6.0.2 on 2026-08-18 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0036_alter_papertrade_broker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papertrade',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
