# Generated by Django 6.0.2 on 2026-08-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0037_alter_papertrade_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='take_profit',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
