# Generated by Django 6.0.2 on 2026-08-25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0038_papertrade_take_profit'),
    ]

    operations = [
        migrations.AddField(
            model_name='papertrade',
            name='stop_order_id',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
