"""
Django settings for portfolio_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# FX rates
USD_CAD_RATE = float(os.getenv('USD_CAD_RATE', '1.36'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6=^b)&0^4goj9ix@877=&ka%6y+lfci!e$kw_hh#-hi@0u$qju'
GEMINI_AI_API_KEY = os.getenv('GEMINI_AI_API_KEY') or os.getenv('GEMINI_API_KEY')
GEMINI_AI_MODEL = os.getenv('GEMINI_AI_MODEL', 'models/gemini-2.5-flash')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.2.92',
    '100.88.73.110',
    'backend',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'rest_framework',
    'corsheaders',
    'portfolio',
    'analysis',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'portfolio.middleware.DisableCSRFMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://192.168.2.92:3001',
    'http://100.88.73.110:3001',
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://192.168.2.92:3001',
    'http://100.88.73.110:3001',
]

# Dev LAN convenience
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True

ROOT_URLCONF = 'portfolio_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_backend.wsgi.application'
ASGI_APPLICATION = 'portfolio_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()
if DB_ENGINE in {'postgres', 'postgresql', 'psql'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'personalstock'),
            'USER': os.getenv('DB_USER', 'personalstock'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'postgres'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db' / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'portfolio.pagination.DefaultPagination',
    'PAGE_SIZE': 25,
}

# Celery / Redis
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'

# Cache Django (2026-08-20) -- avant ce fix, aucun CACHES n'était défini
# donc Django retombait sur son défaut, LocMemCache : un cache EN MÉMOIRE
# DU PROCESS, jamais partagé entre workers et jamais persisté (perdu à
# chaque redémarrage/déploiement de conteneur -- ce qui arrive à chaque
# `docker compose up --force-recreate`, très fréquent sur ce projet).
# Confirmé en direct le 2026-08-20 en testant portfolio/services/
# penny_risk_screen.py : un cache.set() dans un process invisible dans un
# second process séparé, comme attendu d'un cache non partagé. Cette même
# limitation était déjà documentée le 2026-08-13 (_circuit_breaker_redis_
# client, item 9 TECH_DEBT_NOTES.md) mais corrigée seulement pour ce cas
# précis (client Redis brut, pas via ce framework), pas globalement --
# _fetch_insider_buying (analysis/services/quant_filter.py) utilise
# encore ce cache.* générique depuis le 2026-08-16 sans que personne ne
# l'ait remarqué avant aujourd'hui.
#
# DB Redis 1 (pas 0, qui sert déjà de broker Celery ET de couche Channels
# -- voir CHANNEL_LAYERS plus bas) + KEY_PREFIX dédié, pour ne jamais
# entrer en collision avec les clés internes de ces deux autres systèmes
# ni avec le client Redis brut du circuit breaker (lui-même sur DB 0).
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': REDIS_URL.rsplit('/', 1)[0] + '/1',
        'KEY_PREFIX': 'djcache',
    },
}

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://localhost:6379/0')],
        },
    },
}

# Routage explicite : le scan fondamental (analysis) et son check hebdo
# vont dans une queue dédiée ('analysis_queue'), consommée par un worker
# séparé (celery-worker-analysis, voir docker-compose.yml). Objectif :
# ces tâches basse-fréquence ne restent plus jamais coincées derrière le
# flot de tâches haute-fréquence (penny_sniper_alert, monitor_hive_trade,
# monitor_active_trade, etc.) sur le worker principal --pool=solo
# mono-thread. Additif pur : aucune tâche existante n'est reroutée, tout
# ce qui n'est pas listé ici continue d'aller sur la queue par défaut
# ('celery'), consommée par le worker existant comme avant.
CELERY_TASK_ROUTES = {
    'analysis.tasks.run_daily_scan': {'queue': 'analysis_queue'},
    'analysis.tasks.check_rejection_outcomes': {'queue': 'analysis_queue'},
    'analysis.tasks.run_broad_index_scan': {'queue': 'analysis_queue'},
    'analysis.tasks.monitor_lab_positions': {'queue': 'analysis_queue'},
    'analysis.tasks.generate_lab_weekly_suggestions': {'queue': 'analysis_queue'},
}

CELERY_BEAT_SCHEDULE = {
    'fetch-prices-2min': {
        'task': 'portfolio.tasks.fetch_prices_hourly',
        'schedule': crontab(minute='*/10', hour='9-16', day_of_week='mon-fri'),
    },
    'fetch-fundamentals-12h': {
        'task': 'portfolio.tasks.fetch_fundamentals_daily',
        'schedule': crontab(minute=10, hour=6),
    },
    'fetch-news-daily': {
        'task': 'portfolio.tasks.fetch_news_daily',
        'schedule': crontab(minute=0, hour=6),
    },
    'fetch-finnhub-news-daily': {
        'task': 'portfolio.tasks.fetch_finnhub_news_daily',
        'schedule': crontab(minute=30, hour=6),
    },
    'fetch-google-news-daily': {
        'task': 'portfolio.tasks.fetch_google_news_daily',
        'schedule': crontab(minute=45, hour=6),
    },
    'fetch-macro-daily': {
        'task': 'portfolio.tasks.fetch_macro_daily',
        'schedule': crontab(minute=5, hour=7),
    },
    'fetch-press-releases-hourly': {
        'task': 'portfolio.tasks.fetch_press_releases_hourly',
        'schedule': crontab(minute=10, hour='9-16', day_of_week='mon-fri'),
    },
    'calculate-drip-weekly': {
        'task': 'portfolio.tasks.calculate_drip_weekly',
        'schedule': crontab(minute=0, hour=7, day_of_week='mon'),
    },
    'calculate-drip-monthly': {
        'task': 'portfolio.tasks.calculate_drip_monthly',
        'schedule': crontab(minute=0, hour=7, day_of_month='1'),
    },
    'check-alerts-hourly': {
        'task': 'portfolio.tasks.check_alerts',
        'schedule': crontab(minute=15, hour='9-16', day_of_week='mon-fri'),
    },
    'weekly-ai-forecast': {
        'task': 'portfolio.tasks.weekly_ai_forecast',
        'schedule': crontab(minute=30, hour=6, day_of_week='sun'),
    },
    'event-risk-daily': {
        'task': 'portfolio.tasks.check_event_risks',
        'schedule': crontab(minute=0, hour=8),
    },
    'portfolio-digest-weekly': {
        'task': 'portfolio.tasks.generate_portfolio_digest',
        'schedule': crontab(minute=0, hour=9, day_of_week='sun'),
    },
    'morning-scout-report-daily': {
        'task': 'portfolio.tasks.send_morning_scout_report',
        'schedule': crontab(minute=0, hour=9),
    },
    'premarket-deep-scan-0830': {
        'task': 'portfolio.tasks.premarket_deep_scan',
        'schedule': crontab(minute=30, hour=8, day_of_week='mon-fri'),
    },
    'premarket-ai-prediction-0900': {
        'task': 'portfolio.tasks.premarket_ai_prediction',
        'schedule': crontab(minute=0, hour=9, day_of_week='mon-fri'),
    },
    'match-plan-0945': {
        'task': 'portfolio.tasks.send_match_plan_report',
        'schedule': crontab(minute=45, hour=9, day_of_week='mon-fri'),
    },
    'optimizer-snapshot-open-0935': {
        'task': 'portfolio.tasks.cache_optimizer_snapshot',
        'schedule': crontab(minute=35, hour=9, day_of_week='mon-fri'),
        'kwargs': {'fast': True},
    },
    'optimizer-snapshot-midday-1230': {
        'task': 'portfolio.tasks.cache_optimizer_snapshot',
        'schedule': crontab(minute=30, hour=12, day_of_week='mon-fri'),
        'kwargs': {'fast': True},
    },
    'optimizer-snapshot-close-1605': {
        'task': 'portfolio.tasks.cache_optimizer_snapshot',
        'schedule': crontab(minute=5, hour=16, day_of_week='mon-fri'),
        'kwargs': {'fast': True},
    },
    'deepseek-open-0945': {
        'task': 'portfolio.tasks.run_morning_ai_analysis',
        'schedule': crontab(minute=45, hour=9, day_of_week='mon-fri'),
    },
    'update-user-preferences-daily': {
        'task': 'portfolio.tasks.update_user_preferences',
        'schedule': crontab(minute=30, hour=9),
    },
    'penny-signals-twice-daily': {
        'task': 'portfolio.tasks.generate_penny_signals',
        'schedule': crontab(minute=15, hour='10,16'),
    },
    'penny-ai-scout-hourly': {
        'task': 'portfolio.tasks.run_penny_ai_scout',
        'schedule': crontab(minute=0, hour='9-16', day_of_week='mon-fri'),
    },
    'backtest-retrain-guard-daily': {
        'task': 'portfolio.tasks.backtest_retrain_guard',
        'schedule': crontab(minute=20, hour=7),
    },
    'paper-trades-15min': {
        'task': 'portfolio.tasks.execute_paper_trades',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'refresh-ai-bluechip-watchlist-hourly': {
        'task': 'portfolio.tasks.refresh_ai_bluechip_watchlist',
        'schedule': crontab(minute=5, hour='8-16', day_of_week='mon-fri'),
    },
    'bluechip-dip-scanner-0900': {
        'task': 'portfolio.tasks.bluechip_dip_scanner',
        'schedule': crontab(minute=0, hour='9,13', day_of_week='mon-fri'),
    },
    'refresh-ai-penny-watchlist-hourly': {
        'task': 'portfolio.tasks.refresh_ai_penny_watchlist',
        'schedule': crontab(minute=10, hour='8-16', day_of_week='mon-fri'),
    },
    'penny-opportunity-scanner-0930': {
        'task': 'portfolio.tasks.penny_opportunity_scanner',
        'schedule': crontab(minute=30, hour='9,13', day_of_week='mon-fri'),
    },
    'paper-trades-ai-bluechip-15min': {
        'task': 'portfolio.tasks.execute_paper_trades_ai_bluechip',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'paper-trades-ai-penny-15min': {
        'task': 'portfolio.tasks.execute_paper_trades_ai_penny',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'paper-trades-ai-crypto-15min': {
        'task': 'portfolio.tasks.execute_paper_trades_ai_crypto',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-watchlist-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_watchlist',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-bluechip-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_ai_bluechip',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-penny-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_ai_penny',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-sync-5min': {
        'task': 'portfolio.tasks.sync_alpaca_paper_trades',
        'schedule': crontab(minute='*/5', hour='9-16', day_of_week='mon-fri'),
    },
    'crypto-scan-15min': {
        'task': 'portfolio.tasks.task_crypto_scan',
        'schedule': crontab(minute='*/30', hour='9-16', day_of_week='mon-fri'),
    },
    'market-scanner-5min': {
        'task': 'portfolio.tasks.market_scanner_task',
        'schedule': crontab(minute='*/10', hour='9-16', day_of_week='mon-fri'),
    },
    'active-signal-monitor-1min': {
        'task': 'portfolio.tasks.monitor_active_signals',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    # Renommé le 2026-08-13 (TECH_DEBT_NOTES.md item 4) : le nom disait
    # "30s" mais l'intervalle réel était timedelta(seconds=120) = 2 min,
    # ET la tâche tournait 24/7 (aucune restriction horaire), contrairement
    # à toutes les autres tâches de surveillance de ce fichier -- confirmé
    # avec l'utilisateur que c'était un oubli, pas voulu (pas de
    # surveillance overnight intentionnelle). Restreint aux heures de
    # marché comme 'active-signal-monitor-1min' juste au-dessus (même
    # cadence de 2 min, même fenêtre) plutôt que de laisser tourner pour
    # rien marché fermé.
    'tsx-guardian-120s': {
        'task': 'portfolio.tasks.monitor_active_trade',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'paper-trade-retrain-daily': {
        'task': 'portfolio.tasks.retrain_from_paper_trades_daily',
        'schedule': crontab(minute=40, hour=7),
    },
    'model-evaluation-daily': {
        'task': 'portfolio.tasks.compute_model_evaluation_daily',
        'schedule': crontab(minute=50, hour=7),
    },
    'model-drift-check-daily': {
        'task': 'portfolio.tasks.detect_model_drift',
        'schedule': crontab(minute=10, hour=8),
    },
    'cleanup-system-logs-weekly': {
        'task': 'portfolio.tasks.cleanup_system_logs',
        'schedule': crontab(minute=0, hour=3, day_of_week='sun'),
    },
    'data-pipeline-daily': {
        'task': 'portfolio.tasks.ensure_data_pipeline_daily',
        'schedule': crontab(minute=10, hour=7),
    },
    'data-qa-daily': {
        'task': 'portfolio.tasks.compute_data_qa_daily',
        'schedule': crontab(minute=20, hour=7),
    },
    'continuous-evaluation-daily': {
        'task': 'portfolio.tasks.compute_continuous_evaluation_daily',
        'schedule': crontab(minute=35, hour=7),
    },
    'audit-portfolio-matin': {
        'task': 'portfolio.tasks.task_audit_portfolio_complet',
        'schedule': crontab(hour=9, minute=35, day_of_week='mon-fri'),
        'kwargs': {'is_close': False},
    },
    'audit-portfolio-cloture': {
        'task': 'portfolio.tasks.task_audit_portfolio_complet',
        'schedule': crontab(hour=16, minute=0, day_of_week='mon-fri'),
        'kwargs': {'is_close': True},
    },
    'deep-learning-retro-nightly': {
        'task': 'portfolio.tasks.deep_learning_retro_train',
        'schedule': crontab(hour=2, minute=10),
    },
    'drift-retrain-daily': {
        'task': 'portfolio.tasks.auto_retrain_on_drift_daily',
        'schedule': crontab(minute=45, hour=7),
    },
    'nightly-closed-market-retrain': {
        'task': 'portfolio.tasks.nightly_closed_market_retrain',
        'schedule': crontab(minute=0, hour=2),
    },
    'model-rollback-daily': {
        'task': 'portfolio.tasks.auto_rollback_models_daily',
        'schedule': crontab(minute=55, hour=7),
    },
    'cleanup-taskrunlog-daily': {
        'task': 'portfolio.tasks.cleanup_task_run_logs',
        'schedule': crontab(minute=15, hour=2),
    },
    'trading-journal-daily': {
        'task': 'portfolio.tasks.generate_trading_journal_daily',
        'schedule': crontab(minute=30, hour=20),
    },
    'daily-bot-journal-2005': {
        'task': 'portfolio.tasks.send_daily_bot_journal',
        'schedule': crontab(minute=5, hour=20),
    },
    'weekend-deep-research-sat': {
        'task': 'portfolio.tasks.weekend_deep_research',
        'schedule': crontab(minute=0, hour=6, day_of_week='sat'),
    },
    'economic-calendar-weekly': {
        'task': 'portfolio.tasks.economic_calendar_module',
        'schedule': crontab(minute=0, hour=6, day_of_week='sun'),
    },
    'sunday-evening-briefing': {
        'task': 'portfolio.tasks.sunday_evening_briefing',
        'schedule': crontab(minute=0, hour=20, day_of_week='sun'),
    },
    'morning-status-check': {
        'task': 'portfolio.tasks.morning_status_check',
        'schedule': crontab(minute=20, hour=9, day_of_week='mon-fri'),
    },
    'nightly-intraday-retrain': {
        'task': 'portfolio.tasks.nightly_intraday_retrain',
        'schedule': crontab(minute=30, hour=0),
    },
    'nightly-summary-report': {
        'task': 'portfolio.tasks.nightly_summary_report',
        'schedule': crontab(minute=0, hour=8),
    },
    'morning-log-email': {
        'task': 'portfolio.tasks.send_morning_log_email',
        'schedule': crontab(minute=5, hour=8, day_of_week='mon-fri'),
        'kwargs': {'limit': 200},
    },
    'premarket-report-0845': {
        'task': 'portfolio.tasks.send_telegram_report',
        'schedule': crontab(minute=45, hour=8, day_of_week='mon-fri'),
        'args': ('premarket',),
    },
    'validation-report-0945': {
        'task': 'portfolio.tasks.send_telegram_report',
        'schedule': crontab(minute=45, hour=9, day_of_week='mon-fri'),
        'args': ('validation',),
    },
    'institutional-flow-1030': {
        'task': 'portfolio.tasks.send_telegram_report',
        'schedule': crontab(minute=30, hour=10, day_of_week='mon-fri'),
        'args': ('institutional',),
    },
    'daily-profit-tracker': {
        'task': 'portfolio.tasks.daily_profit_tracker',
        'schedule': crontab(minute=30, hour=16, day_of_week='mon-fri'),
    },
    'daily-performance-report': {
        'task': 'portfolio.tasks.generate_daily_performance_report',
        'schedule': crontab(minute=5, hour=17, day_of_week='mon-fri'),
    },
    'monitor-my-portfolio-hourly': {
        'task': 'portfolio.tasks.monitor_my_portfolio',
        'schedule': crontab(minute=0, hour='9-16', day_of_week='mon-fri'),
    },
    'portfolio-news-brief-morning': {
        'task': 'portfolio.tasks.portfolio_news_brief',
        'schedule': crontab(minute=0, hour=9, day_of_week='mon-fri'),
    },
    'hive-opening-rebound-alert': {
        'task': 'portfolio.tasks.hive_opening_rebound_alert',
        'schedule': crontab(minute=35, hour=9, day_of_week='mon-fri'),
    },
    'value-hunter-hourly': {
        'task': 'portfolio.tasks.value_hunter_scan',
        'schedule': crontab(minute=0, hour='9-16', day_of_week='mon-fri'),
    },
    'value-hunter-report-1015': {
        'task': 'portfolio.tasks.send_value_hunter_report',
        'schedule': crontab(minute=15, hour=10, day_of_week='mon-fri'),
    },
    'penny-rebound-diagnostic': {
        'task': 'portfolio.tasks.send_penny_rebound_diagnostic',
        'schedule': crontab(minute=35, hour=9, day_of_week='mon-fri'),
    },
    'penny-rebound-diagnostic-confirm': {
        'task': 'portfolio.tasks.send_penny_rebound_diagnostic',
        'schedule': crontab(minute=45, hour=9, day_of_week='mon-fri'),
    },
    'monitor-hive-trade-1min': {
        'task': 'portfolio.tasks.monitor_hive_trade',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'penny-sniper-1min': {
        'task': 'portfolio.tasks.penny_sniper_alert',
        'schedule': crontab(minute='*/2', hour='9-16', day_of_week='mon-fri'),
    },
    'discover-opportunities-morning': {
        'task': 'portfolio.tasks.auto_discover_top_movers',
        'schedule': crontab(hour=14, minute=30, day_of_week='mon-fri'),
    },
    'market-scan-hourly': {
        'task': 'portfolio.tasks.scan_market_for_opportunities',
        'schedule': crontab(minute=0, hour='10-16', day_of_week='mon-fri'),
    },
    # Module Analyse fondamentale (app 'analysis') — tables et sandbox
    # ('FUNDAMENTAL_LAB') dédiées, aucun chevauchement avec les jobs ci-dessus.
    # Deux scans/jour (2026-08-10) : ouverture + fermeture ET. CELERY_TIMEZONE
    # = 'America/New_York' (vrai fuseau IANA, pas un offset fixe) donc le
    # passage EST/EDT est géré automatiquement, aucun ajustement manuel requis.
    'morning-fundamental-scan': {
        'task': 'analysis.tasks.run_daily_scan',
        'schedule': crontab(hour=9, minute=45, day_of_week='mon-fri'),  # 15 min après l'ouverture ET
    },
    'daily-fundamental-scan': {
        'task': 'analysis.tasks.run_daily_scan',
        'schedule': crontab(hour=16, minute=30, day_of_week='mon-fri'),  # 30 min après la fermeture ET
    },
    'weekly-rejection-outcome-check': {
        'task': 'analysis.tasks.check_rejection_outcomes',
        'schedule': crontab(hour=6, minute=0, day_of_week='mon'),
    },
    # Partie 3 (2026-08-14) : résumé hebdomadaire de patterns simples sur les
    # positions FUNDAMENTAL_LAB fermées -- après check_rejection_outcomes
    # (même matinée, hors marché), jamais d'action automatique, seulement
    # une suggestion stockée pour la page Analytics & ML Lab.
    'weekly-lab-suggestions': {
        'task': 'analysis.tasks.generate_lab_weekly_suggestions',
        'schedule': crontab(hour=6, minute=30, day_of_week='mon'),
    },
    # Balayage large hebdomadaire S&P 500 + TSX Composite (2026-08-11) --
    # alimente CustomWatchlistTicker, PAS l'univers quotidien tant que
    # universe_source='combined' n'est pas activé sur un preset (voir
    # docs/TECH_DEBT_NOTES.md). Dimanche soir, largement hors marché --
    # tourne potentiellement plusieurs heures (700+ tickers, plusieurs
    # appels yfinance chacun), aucune urgence de timing donc pas de souci
    # avec la durée. N'ajoute pas au "burst" du item 7 (Beat) puisque
    # c'est le seul job à cet horaire précis.
    'weekly-broad-index-scan': {
        'task': 'analysis.tasks.run_broad_index_scan',
        'schedule': crontab(hour=20, minute=0, day_of_week='sun'),
    },
    # Exécution des trades SWING crypto sur Alpaca paper (2026-08-18,
    # passé de 4h à 15 min le même jour -- marché crypto 24/7, coût réseau/
    # calcul négligeable pour 2 symboles (~22s par run réel mesuré), et le
    # prix "du jour" chez yfinance se met à jour en continu jusqu'à la
    # clôture de la bougie journalière -- vérifier plus souvent capte un
    # vrai recul en formation plus tôt, pas juste du bruit répété). Activé
    # depuis AI_CRYPTO_SWING_ENABLED=true (deploy/.env, 2026-08-18) -- voir
    # _execute_alpaca_paper_trades_for_crypto_swing.
    'crypto-swing-paper-trade': {
        'task': 'portfolio.tasks.crypto_swing_paper_trade_task',
        'schedule': crontab(minute='*/15'),
    },
    # Réentraînement hebdomadaire du pipeline SWING crypto (2026-08-18) --
    # 21h30 ET, après weekly-broad-index-scan (20h00) pour éviter la
    # contention de ressources pendant son propre run (potentiellement
    # long). AI_CRYPTO reste désactivé (pas de watchlist configurée) --
    # cette tâche ne fait que réentraîner/réévaluer le modèle en arrière-
    # plan, elle ne trade rien. Rejet silencieux (log SUCCESS, pas
    # d'alerte) si le modèle ne franchit pas les portes de qualité --
    # comportement voulu, voir retrain_crypto_swing_model_weekly.
    'weekly-crypto-swing-retrain': {
        'task': 'portfolio.tasks.retrain_crypto_swing_model_weekly',
        'schedule': crontab(hour=21, minute=30, day_of_week='sun'),
    },
    # Red flags pennystock AI_PENNY (2026-08-20) -- going concern, dette
    # convertible toxique, 8-K récent, cash runway, dilution ATM (SEC
    # EDGAR + yfinance). Hebdomadaire seulement : ces données ne changent
    # qu'au rythme trimestriel des dépôts -- voir refresh_penny_red_flags_
    # weekly. 22h00 dimanche, après le réentraînement crypto (21h30) pour
    # éviter la contention.
    'weekly-penny-red-flags-refresh': {
        'task': 'portfolio.tasks.refresh_penny_red_flags_weekly',
        'schedule': crontab(hour=22, minute=0, day_of_week='sun'),
    },
    # Stop-loss minimal pour les positions FUNDAMENTAL_LAB à ordre Alpaca
    # réel (broker='ALPACA_LAB', voir docs/TECH_DEBT_NOTES.md item 11,
    # Partie B 2026-08-11) -- aucun mécanisme de sortie n'existait avant ça.
    # */10 pendant les heures de marché ET, cohérent avec les autres tâches
    # de surveillance de ce fichier.
    'monitor-lab-positions': {
        'task': 'analysis.tasks.monitor_lab_positions',
        'schedule': crontab(minute='*/10', hour='9-16', day_of_week='mon-fri'),
    },
}

AFTER_HOURS_TASKS_ENABLED = os.getenv('AFTER_HOURS_TASKS_ENABLED', 'false').lower() in {
    '1',
    'true',
    'yes',
    'on',
}

if not AFTER_HOURS_TASKS_ENABLED:
    # cleanup-taskrunlog-daily et cleanup-system-logs-weekly sont sortis de
    # cette liste (2026-08-10) : pur ménage de logs (DELETE sur de vieilles
    # lignes), aucun impact sur le trading live, contrairement au reste de ce
    # lot (retraining/rollback de modèles notamment) qui reste désactivé par
    # défaut ici. Ils tournent maintenant indépendamment de
    # AFTER_HOURS_TASKS_ENABLED -- voir docs/TECH_DEBT_NOTES.md item 6.
    # weekend-deep-research-sat sorti de cette liste le 2026-08-20, même
    # raisonnement que le carve-out du 2026-08-10 ci-dessus : c'est un
    # scan/score en LECTURE SEULE (_analyze_penny_breakouts/_analyze_
    # bluechip_rebounds, aucune commande d'achat/vente), pas un mécanisme
    # de gouvernance ML (retrain/rollback) -- rien à voir avec la décision
    # explicite de ne pas activer ce lot en bloc (item 12, TECH_DEBT_NOTES.md).
    # Trouvé en diagnostiquant pourquoi AI_PENNY ne découvre plus de
    # nouveaux candidats depuis des mois (generate_penny_signals dépend de
    # credentials Reddit jamais configurées) -- ce mécanisme alternatif,
    # scanne directement le marché (yfinance most_actives), pas les
    # mentions sociales, existait déjà tout ce temps, juste jamais activé.
    for task_name in [
        'deep-learning-retro-nightly',
        'nightly-closed-market-retrain',
        'nightly-intraday-retrain',
        'trading-journal-daily',
        'daily-bot-journal-2005',
        'sunday-evening-briefing',
        'economic-calendar-weekly',
        'daily-performance-report',
        'daily-profit-tracker',
        'paper-trade-retrain-daily',
        'model-evaluation-daily',
        'model-drift-check-daily',
        'data-pipeline-daily',
        'data-qa-daily',
        'continuous-evaluation-daily',
        'backtest-retrain-guard-daily',
        'drift-retrain-daily',
        'model-rollback-daily',
    ]:
        CELERY_BEAT_SCHEDULE.pop(task_name, None)

# Alerting / Email (dev defaults)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'alerts@localhost')
ALERT_EMAIL_TO = os.getenv('ALERT_EMAIL_TO', 'langlois88@gmail.com')
ALERT_PRICE_THRESHOLD = float(os.getenv('ALERT_PRICE_THRESHOLD', '1000'))
ALERT_DROP_PCT = float(os.getenv('ALERT_DROP_PCT', '5'))
ALERT_CAPITAL_THRESHOLD = float(os.getenv('ALERT_CAPITAL_THRESHOLD', '10000'))
ALERT_COOLDOWN_HOURS = int(os.getenv('ALERT_COOLDOWN_HOURS', '12'))
ALERT_SMS_TO = os.getenv('ALERT_SMS_TO', '')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')

# Event risk keywords for news scanning
EVENT_RISK_KEYWORDS = [
    'strike',
    'pipeline',
    'spill',
    'lawsuit',
    'regulatory',
    'investigation',
    'recall',
    'bankruptcy',
    'sanctions',
    'outage',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
