"""
Django settings for portfolio_backend project.

Generated by 'django-admin startproject' using Django 4.2.28.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from pathlib import Path

from celery.schedules import crontab

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# FX rates
USD_CAD_RATE = float(os.getenv('USD_CAD_RATE', '1.36'))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-6=^b)&0^4goj9ix@877=&ka%6y+lfci!e$kw_hh#-hi@0u$qju'
GEMINI_AI_API_KEY = os.getenv('GEMINI_AI_API_KEY') or os.getenv('GEMINI_API_KEY')
GEMINI_AI_MODEL = os.getenv('GEMINI_AI_MODEL', 'models/gemini-2.5-flash')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    '192.168.2.92',
    '100.88.73.110',
    'backend',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'channels',
    'rest_framework',
    'corsheaders',
    'portfolio',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://localhost:3001',
    'http://192.168.2.92:3001',
    'http://100.88.73.110:3001',
]

# Dev LAN convenience
CORS_ALLOW_ALL_ORIGINS = True

ROOT_URLCONF = 'portfolio_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'portfolio_backend.wsgi.application'
ASGI_APPLICATION = 'portfolio_backend.asgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()
if DB_ENGINE in {'postgres', 'postgresql', 'psql'}:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DB_NAME', 'personalstock'),
            'USER': os.getenv('DB_USER', 'personalstock'),
            'PASSWORD': os.getenv('DB_PASSWORD', ''),
            'HOST': os.getenv('DB_HOST', 'postgres'),
            'PORT': os.getenv('DB_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db' / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

REST_FRAMEWORK = {
    'DEFAULT_PAGINATION_CLASS': 'portfolio.pagination.DefaultPagination',
    'PAGE_SIZE': 25,
}

# Celery / Redis
REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'America/New_York'

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [os.getenv('REDIS_URL', 'redis://localhost:6379/0')],
        },
    },
}

CELERY_BEAT_SCHEDULE = {
    'fetch-prices-2min': {
        'task': 'portfolio.tasks.fetch_prices_hourly',
        'schedule': crontab(minute='*/2', hour='*'),
    },
    'fetch-fundamentals-12h': {
        'task': 'portfolio.tasks.fetch_fundamentals_daily',
        'schedule': crontab(minute=10, hour='6,18'),
    },
    'fetch-news-daily': {
        'task': 'portfolio.tasks.fetch_news_daily',
        'schedule': crontab(minute=0, hour=6),
    },
    'fetch-finnhub-news-daily': {
        'task': 'portfolio.tasks.fetch_finnhub_news_daily',
        'schedule': crontab(minute=30, hour=6),
    },
    'fetch-google-news-daily': {
        'task': 'portfolio.tasks.fetch_google_news_daily',
        'schedule': crontab(minute=45, hour=6),
    },
    'fetch-macro-daily': {
        'task': 'portfolio.tasks.fetch_macro_daily',
        'schedule': crontab(minute=5, hour=7),
    },
    'fetch-press-releases-hourly': {
        'task': 'portfolio.tasks.fetch_press_releases_hourly',
        'schedule': crontab(minute=10, hour='*'),
    },
    'calculate-drip-weekly': {
        'task': 'portfolio.tasks.calculate_drip_weekly',
        'schedule': crontab(minute=0, hour=7, day_of_week='mon'),
    },
    'calculate-drip-monthly': {
        'task': 'portfolio.tasks.calculate_drip_monthly',
        'schedule': crontab(minute=0, hour=7, day_of_month='1'),
    },
    'check-alerts-hourly': {
        'task': 'portfolio.tasks.check_alerts',
        'schedule': crontab(minute=15, hour='*'),
    },
    'weekly-ai-forecast': {
        'task': 'portfolio.tasks.weekly_ai_forecast',
        'schedule': crontab(minute=30, hour=6, day_of_week='sun'),
    },
    'event-risk-daily': {
        'task': 'portfolio.tasks.check_event_risks',
        'schedule': crontab(minute=0, hour=8),
    },
    'portfolio-digest-weekly': {
        'task': 'portfolio.tasks.generate_portfolio_digest',
        'schedule': crontab(minute=0, hour=9, day_of_week='sun'),
    },
    'morning-scout-report-daily': {
        'task': 'portfolio.tasks.send_morning_scout_report',
        'schedule': crontab(minute=0, hour=9),
    },
    'update-user-preferences-daily': {
        'task': 'portfolio.tasks.update_user_preferences',
        'schedule': crontab(minute=30, hour=9),
    },
    'penny-signals-twice-daily': {
        'task': 'portfolio.tasks.generate_penny_signals',
        'schedule': crontab(minute=15, hour='10,16'),
    },
    'penny-ai-scout-hourly': {
        'task': 'portfolio.tasks.run_penny_ai_scout',
        'schedule': crontab(minute=0, hour='*'),
    },
    'backtest-retrain-guard-daily': {
        'task': 'portfolio.tasks.backtest_retrain_guard',
        'schedule': crontab(minute=20, hour=7),
    },
    'paper-trades-15min': {
        'task': 'portfolio.tasks.execute_paper_trades',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'refresh-ai-bluechip-watchlist-hourly': {
        'task': 'portfolio.tasks.refresh_ai_bluechip_watchlist',
        'schedule': crontab(minute=5, hour='8-16', day_of_week='mon-fri'),
    },
    'refresh-ai-penny-watchlist-hourly': {
        'task': 'portfolio.tasks.refresh_ai_penny_watchlist',
        'schedule': crontab(minute=10, hour='8-16', day_of_week='mon-fri'),
    },
    'paper-trades-ai-bluechip-15min': {
        'task': 'portfolio.tasks.execute_paper_trades_ai_bluechip',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'paper-trades-ai-penny-15min': {
        'task': 'portfolio.tasks.execute_paper_trades_ai_penny',
        'schedule': crontab(minute='*/15', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-watchlist-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_watchlist',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-bluechip-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_ai_bluechip',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-penny-1min': {
        'task': 'portfolio.tasks.execute_alpaca_paper_trades_ai_penny',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'alpaca-paper-sync-5min': {
        'task': 'portfolio.tasks.sync_alpaca_paper_trades',
        'schedule': crontab(minute='*/5', hour='*'),
    },
    'market-scanner-5min': {
        'task': 'portfolio.tasks.market_scanner_task',
        'schedule': crontab(minute='*/5', hour='9-16', day_of_week='mon-fri'),
    },
    'active-signal-monitor-1min': {
        'task': 'portfolio.tasks.monitor_active_signals',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'paper-trade-retrain-daily': {
        'task': 'portfolio.tasks.retrain_from_paper_trades_daily',
        'schedule': crontab(minute=40, hour=7),
    },
    'model-evaluation-daily': {
        'task': 'portfolio.tasks.compute_model_evaluation_daily',
        'schedule': crontab(minute=50, hour=7),
    },
    'data-pipeline-daily': {
        'task': 'portfolio.tasks.ensure_data_pipeline_daily',
        'schedule': crontab(minute=10, hour=7),
    },
    'data-qa-daily': {
        'task': 'portfolio.tasks.compute_data_qa_daily',
        'schedule': crontab(minute=20, hour=7),
    },
    'continuous-evaluation-daily': {
        'task': 'portfolio.tasks.compute_continuous_evaluation_daily',
        'schedule': crontab(minute=35, hour=7),
    },
    'audit-portfolio-matin': {
        'task': 'portfolio.tasks.task_audit_portfolio_complet',
        'schedule': crontab(hour=9, minute=35, day_of_week='mon-fri'),
        'kwargs': {'is_close': False},
    },
    'audit-portfolio-cloture': {
        'task': 'portfolio.tasks.task_audit_portfolio_complet',
        'schedule': crontab(hour=16, minute=0, day_of_week='mon-fri'),
        'kwargs': {'is_close': True},
    },
    'deep-learning-retro-nightly': {
        'task': 'portfolio.tasks.deep_learning_retro_train',
        'schedule': crontab(hour=2, minute=10),
    },
    'drift-retrain-daily': {
        'task': 'portfolio.tasks.auto_retrain_on_drift_daily',
        'schedule': crontab(minute=45, hour=7),
    },
    'nightly-closed-market-retrain': {
        'task': 'portfolio.tasks.nightly_closed_market_retrain',
        'schedule': crontab(minute=0, hour=2),
    },
    'model-rollback-daily': {
        'task': 'portfolio.tasks.auto_rollback_models_daily',
        'schedule': crontab(minute=55, hour=7),
    },
    'cleanup-taskrunlog-daily': {
        'task': 'portfolio.tasks.cleanup_task_run_logs',
        'schedule': crontab(minute=15, hour=2),
    },
    'trading-journal-daily': {
        'task': 'portfolio.tasks.generate_trading_journal_daily',
        'schedule': crontab(minute=30, hour=20),
    },
    'weekend-deep-research-sat': {
        'task': 'portfolio.tasks.weekend_deep_research',
        'schedule': crontab(minute=0, hour=6, day_of_week='sat'),
    },
    'economic-calendar-weekly': {
        'task': 'portfolio.tasks.economic_calendar_module',
        'schedule': crontab(minute=0, hour=6, day_of_week='sun'),
    },
    'sunday-evening-briefing': {
        'task': 'portfolio.tasks.sunday_evening_briefing',
        'schedule': crontab(minute=0, hour=20, day_of_week='sun'),
    },
    'morning-status-check': {
        'task': 'portfolio.tasks.morning_status_check',
        'schedule': crontab(minute=20, hour=9, day_of_week='mon-fri'),
    },
    'daily-profit-tracker': {
        'task': 'portfolio.tasks.daily_profit_tracker',
        'schedule': crontab(minute=30, hour=16, day_of_week='mon-fri'),
    },
    'daily-performance-report': {
        'task': 'portfolio.tasks.generate_daily_performance_report',
        'schedule': crontab(minute=5, hour=17, day_of_week='mon-fri'),
    },
    'monitor-my-portfolio-hourly': {
        'task': 'portfolio.tasks.monitor_my_portfolio',
        'schedule': crontab(minute=0, hour='9-16', day_of_week='mon-fri'),
    },
    'portfolio-news-brief-morning': {
        'task': 'portfolio.tasks.portfolio_news_brief',
        'schedule': crontab(minute=0, hour=9, day_of_week='mon-fri'),
    },
    'hive-opening-rebound-alert': {
        'task': 'portfolio.tasks.hive_opening_rebound_alert',
        'schedule': crontab(minute=35, hour=9, day_of_week='mon-fri'),
    },
    'penny-rebound-diagnostic': {
        'task': 'portfolio.tasks.send_penny_rebound_diagnostic',
        'schedule': crontab(minute=35, hour=9, day_of_week='mon-fri'),
    },
    'penny-rebound-diagnostic-confirm': {
        'task': 'portfolio.tasks.send_penny_rebound_diagnostic',
        'schedule': crontab(minute=45, hour=9, day_of_week='mon-fri'),
    },
    'monitor-hive-trade-1min': {
        'task': 'portfolio.tasks.monitor_hive_trade',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'penny-sniper-1min': {
        'task': 'portfolio.tasks.penny_sniper_alert',
        'schedule': crontab(minute='*/1', hour='9-16', day_of_week='mon-fri'),
    },
    'discover-opportunities-morning': {
        'task': 'portfolio.tasks.auto_discover_top_movers',
        'schedule': crontab(hour=14, minute=30, day_of_week='mon-fri'),
    },
    'market-scan-hourly': {
        'task': 'portfolio.tasks.scan_market_for_opportunities',
        'schedule': crontab(minute=0, hour='10-16', day_of_week='mon-fri'),
    },
}

# Alerting / Email (dev defaults)
EMAIL_BACKEND = os.getenv(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend',
)
EMAIL_HOST = os.getenv('EMAIL_HOST', '')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'true').lower() in {'1', 'true', 'yes', 'on'}
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'false').lower() in {'1', 'true', 'yes', 'on'}
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'alerts@localhost')
ALERT_EMAIL_TO = os.getenv('ALERT_EMAIL_TO', 'langlois88@gmail.com')
ALERT_PRICE_THRESHOLD = float(os.getenv('ALERT_PRICE_THRESHOLD', '1000'))
ALERT_DROP_PCT = float(os.getenv('ALERT_DROP_PCT', '5'))
ALERT_CAPITAL_THRESHOLD = float(os.getenv('ALERT_CAPITAL_THRESHOLD', '10000'))
ALERT_COOLDOWN_HOURS = int(os.getenv('ALERT_COOLDOWN_HOURS', '12'))
ALERT_SMS_TO = os.getenv('ALERT_SMS_TO', '')
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN', '')
TWILIO_FROM_NUMBER = os.getenv('TWILIO_FROM_NUMBER', '')

# Event risk keywords for news scanning
EVENT_RISK_KEYWORDS = [
    'strike',
    'pipeline',
    'spill',
    'lawsuit',
    'regulatory',
    'investigation',
    'recall',
    'bankruptcy',
    'sanctions',
    'outage',
]

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
