# Generated by Django 6.1 on 2026-08-09 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('portfolio', '0035_alter_papertrade_sandbox'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('universe_source', models.CharField(default='sandboxes', max_length=20)),
                ('status', models.CharField(choices=[('running', 'running'), ('completed', 'completed'), ('failed', 'failed')], db_index=True, default='running', max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('tickers_scanned', models.IntegerField(default=0)),
                ('candidates_after_quant_filter', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScreenerPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, default='')),
                ('thresholds', models.JSONField(blank=True, default=dict)),
                ('requires_news_check', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScanResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('sector', models.CharField(blank=True, default='', max_length=50)),
                ('quant_score', models.FloatField(default=0.0)),
                ('quant_details', models.JSONField(blank=True, default=dict)),
                ('price_at_scan', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('deepseek_verdict', models.CharField(blank=True, default='', max_length=20)),
                ('deepseek_reasoning', models.TextField(blank=True, default='')),
                ('claude_verdict', models.CharField(blank=True, default='', max_length=20)),
                ('claude_reasoning', models.TextField(blank=True, default='')),
                ('claude_tokens_used', models.IntegerField(default=0)),
                ('final_verdict', models.CharField(choices=[('confirmed', 'confirmed'), ('uncertain', 'uncertain'), ('rejected_deepseek', 'rejected_deepseek'), ('rejected_claude', 'rejected_claude')], db_index=True, max_length=20)),
                ('candle_pattern_detected', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='analysis.scanrun')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='scanrun',
            name='preset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runs', to='analysis.screenerpreset'),
        ),
        migrations.CreateModel(
            name='RejectionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('rejected_by', models.CharField(choices=[('deepseek', 'deepseek'), ('claude', 'claude')], db_index=True, max_length=10)),
                ('reasoning_text', models.TextField(blank=True, default='')),
                ('quant_score', models.FloatField(default=0.0)),
                ('price_at_rejection', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('benchmark_price_at_rejection', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('date_rejection', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('scan_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_log', to='analysis.scanresult')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejection_logs', to='analysis.screenerpreset')),
            ],
            options={
                'ordering': ['-date_rejection'],
            },
        ),
        migrations.CreateModel(
            name='FundamentalLabPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=10)),
                ('entry_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('entry_date', models.DateTimeField()),
                ('benchmark_price_at_entry', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('manually_selected', models.BooleanField(default=False)),
                ('manual_note', models.TextField(blank=True, default='')),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper_trade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portfolio.papertrade')),
                ('scan_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_position', to='analysis.scanresult')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_positions', to='analysis.screenerpreset')),
            ],
            options={
                'ordering': ['-entry_date'],
            },
        ),
        migrations.CreateModel(
            name='RejectionOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('days_since_rejection', models.IntegerField()),
                ('price_then', models.FloatField()),
                ('price_now', models.FloatField()),
                ('return_pct', models.FloatField()),
                ('benchmark_return_pct', models.FloatField()),
                ('alpha', models.FloatField(db_index=True)),
                ('possible_missed_winner', models.BooleanField(db_index=True, default=False)),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('rejection_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='analysis.rejectionlog')),
            ],
            options={
                'ordering': ['-checked_at'],
                'constraints': [models.UniqueConstraint(fields=('rejection_log', 'days_since_rejection'), name='analysis_one_outcome_per_window')],
            },
        ),
        migrations.AddIndex(
            model_name='scanresult',
            index=models.Index(fields=['ticker', 'created_at'], name='analysis_scanres_tkr_dt'),
        ),
    ]
