# Generated by Django 6.0.2 on 2026-08-10 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scanresult',
            name='verdict_source',
            field=models.CharField(blank=True, choices=[('single_call', 'single_call'), ('llm_consensus', 'llm_consensus'), ('llm_disagreement', 'llm_disagreement')], default='single_call', max_length=20),
        ),
    ]
