# Generated by Django 6.1 on 2026-08-11 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0002_scanresult_verdict_source'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomWatchlistTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20, unique=True)),
                ('source_index', models.CharField(choices=[('SP500', 'SP500'), ('TSX', 'TSX')], max_length=20)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_confirmed', models.DateTimeField(auto_now=True)),
                ('consecutive_weeks_missed', models.IntegerField(default=0)),
                ('piotroski_score', models.IntegerField(blank=True, null=True)),
                ('altman_z_score', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'ordering': ['-last_confirmed'],
            },
        ),
    ]
