# Generated by Django 6.1 on 2026-08-13 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0003_customwatchlistticker'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManualTickerCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(db_index=True, max_length=20)),
                ('checked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('sector', models.CharField(blank=True, default='', max_length=50)),
                ('quant_score', models.FloatField(default=0.0)),
                ('quant_details', models.JSONField(blank=True, default=dict)),
                ('price_at_check', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('deepseek_verdict', models.CharField(blank=True, default='', max_length=20)),
                ('deepseek_reasoning', models.TextField(blank=True, default='')),
                ('claude_verdict', models.CharField(blank=True, default='', max_length=20)),
                ('claude_reasoning', models.TextField(blank=True, default='')),
                ('claude_tokens_used', models.IntegerField(default=0)),
                ('final_verdict', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'ordering': ['-checked_at'],
            },
        ),
    ]
