# Generated by Django 6.0.2 on 2026-08-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0007_labweeklysuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundamentallabposition',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('stop_loss', 'stop_loss'), ('manual', 'manual'), ('take_profit', 'take_profit'), ('max_hold_time', 'max_hold_time')], default='', max_length=20),
        ),
    ]
